// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:ccf77d99-f634-4502-84eb-64b5059b9417',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'delighteventplanning-hosting-mobilehub-2082066359',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dgzvs98osh7ga.cloudfront.net',
    'aws_mobile_analytics_app_id': 'eecbdc996f0a4ca186002aff665580da',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '8dabd7bf-2658-4896-bdd9-4ddc06ea363a',
    'aws_project_name': 'delight_event_planning-2019-09-07-23-09-28',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'delighteventplanning-mobilehub-2082066359',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_iJsHegaSd',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '6kja4kvb05o3poe0tv86ckliil',
}

export default awsmobile;
